name: open_api
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: 2.0.0-beta.2
homepage: https://github.com/stablekernel/open-api-dart
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  meta: ^1.1.4
  codable: ^1.0.0-beta

dev_dependencies:
  test: ^0.12.0
