name: open_api
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: 1.0.2
homepage: https://github.com/stablekernel/open-api-dart
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: ^1.1.2

dev_dependencies:
  test: ^0.12.0
